//loaders
export const ENABLE_LOADER = 'ENABLE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// account verification
export const ACCOUNT_VERIFICATION_REQUEST = "ACCOUNT_VERIFICATION_REQUEST";
export const ACCOUNT_VERIFICATION_RESPONSE = 'ACCOUNT_VERIFICATION_RESPONSE';
export const ACCOUNT_VERIFICATION_FAILED = 'ACCOUNT_VERIFICATION_FAILED';

// Register
export const ACCOUNT_REGISTRATION_REQUEST = "ACCOUNT_REGISTRATION_REQUEST";
export const ACCOUNT_REGISTRATION_RESPONSE = 'ACCOUNT_REGISTRATION_RESPONSE';
export const ACCOUNT_REGISTRATION_FAILED = 'ACCOUNT_REGISTRATION_FAILED';

// Logout
export const USER_LOGOUT="USER_LOGOUT"

export const APPOINTMENT_SELECTED = 'APPOINTMENT_SELECTED';
