//loaders
export const ENABLE_LOADER = 'ENABLE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';

// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// Account verification
export const ACCOUNT_VERIFICATION_REQUEST = "ACCOUNT_VERIFICATION_REQUEST";
export const ACCOUNT_VERIFICATION_RESPONSE = 'ACCOUNT_VERIFICATION_RESPONSE';
export const ACCOUNT_VERIFICATION_FAILED = 'ACCOUNT_VERIFICATION_FAILED';

// Register
export const ACCOUNT_REGISTRATION_REQUEST = "ACCOUNT_REGISTRATION_REQUEST";
export const ACCOUNT_REGISTRATION_RESPONSE = 'ACCOUNT_REGISTRATION_RESPONSE';
export const ACCOUNT_REGISTRATION_FAILED = 'ACCOUNT_REGISTRATION_FAILED';

// Logout
export const USER_LOGOUT="USER_LOGOUT"

// Instructor
export const INSTRUCTOR_FETCH_LIST_REQUEST = "INSTRUCTOR_FETCH_LIST_REQUEST"
export const INSTRUCTOR_FETCH_LIST_RESPONSE = "INSTRUCTOR_FETCH_LIST_RESPONSE"
export const INSTRUCTOR_FETCH_PK_REQUEST = "INSTRUCTOR_FETCH_PK_REQUEST"
export const INSTRUCTOR_LIST_REFRESH_TOGGLE = "INSTRUCTOR_LIST_REFRESH_TOGGLE"

// Token
export const TOKEN_REFRESH_REQUEST = "TOKEN_REFRESH_REQUEST"
export const TOKEN_REFRESH_RESPONSE = "TOKEN_REFRESH_RESPONSE"


export const APPOINTMENT_SELECTED = 'APPOINTMENT_SELECTED';
